# Site settings
title: "Nevin Valsaraj"
description: "Website of Nevin Valsaraj hosted on GitHub Pages"
baseurl: ""
url: "http://nevinvalsaraj.com"

# Build settings
markdown: kramdown
permalink: /blog/:title
highlighter: rouge
source: docs
