# Site settings
title: "Nevin Valsaraj"
description: "Website of Nevin Valsaraj hosted on GitHub Pages"
baseurl: ""
url: "http://nevinvalsaraj.github.io"

# Build settings
markdown: kramdown
permalink: /blog/:title
highlighter: rouge
