# Site settings
title: "Nevin Valsaraj"
description: "Website of Nevin Valsaraj hosted on GitHub Pages"
baseurl: ""
url: "http://routeaccess.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
