# Site settings
title: "Nevin Valsaraj"
description: "Website of Nevin Valsaraj hosted on GitHub Pages"
baseurl: ""
url: "http://routeaccess.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# For jekyll-image-tag plugin
image:
    source: resources/posts
    output: generated
    presets:
        post-inline-2:
            attr:
                class: post-img
            width: 480
